# Explore Mosqlimate Data

Test downloading and exploring the data made available through the Mosqlimate platform.

In [1]:
import os
from pathlib import Path

import epiweeks
import mosqlient
import numpy as np
import pandas as pd
import plotly.graph_objects as go
import plotly.express as px


print(os.getcwd())
ROOT_DIRPATH = Path("../..")

# ---- Helpers
def save_tmp_plotly_fig(_fig, _name, _dir=".local"):
    _fpath = ROOT_DIRPATH / Path(f"{_dir}/{_name}.html")
    _fpath.parent.mkdir(exist_ok=True, parents=True)
    _fig.write_html(_fpath, include_plotlyjs="cdn")

/home/paulo_ventura/Inframind/IMDC2026/3rd_imdc_ifgw_inframind-proteus/src/prototypes

# Demographic data

REQUIRED to run the following cell groups

In [2]:
imdc_regional_df = pd.read_csv("../../data/data_imdc_2026/map_regional_health.csv")
imdc_population_df = pd.read_csv("../../data/data_imdc_2026/datasus_population_2001_2025.csv.gz")


imdc_regional_df
# imdc_population_df

,macroregion_code,macroregion_name,uf_code,uf,uf_name,macroregional_geocode,macroregional_name,regional_geocode,regional_name,geocode,geocode_name
0,1,Norte,12,AC,Acre,1201,MACRO UNICA - AC,12002,BAIXO ACRE E PURUS,1200013,AC - ACRELANDIA
1,1,Norte,12,AC,Acre,1201,MACRO UNICA - AC,12001,ALTO ACRE,1200054,AC - ASSIS BRASIL
2,1,Norte,12,AC,Acre,1201,MACRO UNICA - AC,12001,ALTO ACRE,1200104,AC - BRASILEIA
3,1,Norte,12,AC,Acre,1201,MACRO UNICA - AC,12002,BAIXO ACRE E PURUS,1200138,AC - BUJARI
4,1,Norte,12,AC,Acre,1201,MACRO UNICA - AC,12002,BAIXO ACRE E PURUS,1200179,AC - CAPIXABA
...,...,...,...,...,...,...,...,...,...,...,...
5565,1,Norte,17,TO,Tocantins,1701,MACRORREGIAO DE SAUDE NORTE,17002,BICO DO PAPAGAIO,1721208,TO - TOCANTINOPOLIS
5566,1,Norte,17,TO,Tocantins,1701,MACRORREGIAO DE SAUDE NORTE,17004,CERRADO TOCANTINS ARAGUAIA,1721257,TO - TUPIRAMA
5567,1,Norte,17,TO,Tocantins,1701,MACRORREGIAO DE SAUDE NORTE,17004,CERRADO TOCANTINS ARAGUAIA,1721307,TO - TUPIRATINS
5568,1,Norte,17,TO,Tocantins,1701,MACRORREGIAO DE SAUDE NORTE,17001,MEDIO NORTE ARAGUAIA,1722081,TO - WANDERLANDIA
5569,1,Norte,17,TO,Tocantins,1701,MACRORREGIAO DE SAUDE NORTE,17001,MEDIO NORTE ARAGUAIA,1722107,TO - XAMBIOA

## Dengue data

In [3]:
df = pd.read_csv("../../data/data_imdc_2026/dengue.csv.gz", parse_dates=["date"])


imdc_dengue_df = df
df

,geocode,date,casos,epiweek,uf,macroregional_geocode,regional_geocode,uf_code,target_city,train_1,target_1,train_2,target_2,train_3,target_3,train_4,target_4,disease
0,3301900,2010-01-03,5,201001,RJ,3312,33006,33,False,True,False,True,False,True,False,True,False,dengue
1,1504505,2010-01-03,0,201001,PA,1512,15014,15,False,True,False,True,False,True,False,True,False,dengue
2,1503077,2010-01-03,0,201001,PA,1511,15008,15,False,True,False,True,False,True,False,True,False,dengue
3,2106409,2010-01-03,0,201001,MA,2110,21006,21,False,True,False,True,False,True,False,True,False,dengue
4,3135704,2010-01-03,0,201001,MG,3103,31024,31,False,True,False,True,False,True,False,True,False,dengue
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4706645,3531506,2026-03-08,0,202610,SP,3530,35052,35,False,False,False,False,False,False,False,False,True,dengue
4706646,3513603,2026-03-08,0,202610,SP,3526,35172,35,False,False,False,False,False,False,False,False,True,dengue
4706647,3502309,2026-03-08,0,202610,SP,3518,35063,35,False,False,False,False,False,False,False,False,True,dengue
4706648,3556107,2026-03-08,0,202610,SP,3531,35157,35,False,False,False,False,False,False,False,False,True,dengue
4706649,2202251,2026-03-08,0,202610,PI,2210,22011,22,False,False,False,False,False,False,False,False,True,dengue

In [ ]:
# Visualize state-level cases and case incidence
# -----------------------
df = imdc_dengue_df.copy()

# --- Add year and population data
df["year"] = df["date"].dt.year
df = df.merge(imdc_population_df, on=["geocode", "year"])


# --- Aggregate and calculate per-populaiton incidence
state_aggr_df = df.groupby(["uf", "date"]).agg({"casos": "sum", "population": "sum"})
# state_sr = df.groupby(["uf", "date"])["casos"].sum()

state_aggr_df["case_inc_100k"] = state_aggr_df["casos"] / state_aggr_df["population"] * 1E5

# ---- Plot abs cases
fig = px.line(state_aggr_df.reset_index(), x="date", y="casos", color="uf")
fig.show()
save_tmp_plotly_fig(fig, "dengue_cases_uf")

# --- Plot case incidence rate by 100k population
fig = px.line(state_aggr_df.reset_index(), x="date", y="case_inc_100k", color="uf")
fig.show()
save_tmp_plotly_fig(fig, "dengue_cases_inc_uf")

In [ ]:
# TEST: Select data to evaluate the prototype renewal model
date_zero = pd.Timestamp("2023-10-02")
num_weeks = 50
uf = "AP"

# ---
date_start = date_zero
date_end = date_zero + pd.Timedelta(weeks=num_weeks)

df = imdc_dengue_df
df = df.loc[
    (df["uf"] == uf)
    # (df["date"].between(date_start, date_end))
]

sr: pd.Series = df.groupby(["date"])["casos"].sum()

fpath = Path(f"../../.local/dengue/cases_tseries_{uf}.csv")
fpath.parent.mkdir(parents=True, exist_ok=True)
sr.to_csv(fpath)

sr

# Climate data

In [ ]:
df = pd.read_csv("../../data/data_imdc_2026/climate.csv.gz", parse_dates=["date"])

imdc_climate_df = df

imdc_climate_df

In [ ]:
df = imdc_climate_df

# --- Map municipalities into UFs
imdc_regional_df   # REQUIRES PREVIOUS CELL GROUP TO BE RUN
df = df.merge(imdc_regional_df[["geocode", "uf", "uf_name"]], on="geocode")

# # --- Add the year based on reference date
df["year"] = df["date"].dt.year

# --- Add population based on year and municipality
df = df.merge(imdc_population_df[:], on=["geocode", "year"])

# --- Aggreagate spatially by UF in multiple ways

named_aggs = dict()
#  ^ Dictionary of aggregations. Each entry is one aggregate with source columns, target variables and aggr function

# Simple average temperature, all municipalities treated equally
named_aggs["mean_temp_med"] = pd.NamedAgg(column="temp_med", aggfunc="mean")

# Weighted average temperature by municipality population
named_aggs["weighted_mean_temp_med"] = pd.NamedAgg(
    column="temp_med",
    aggfunc=lambda x: (x * df.loc[x.index, "population"]).sum() / df.loc[x.index, "population"].sum()
)


# -
spatial_agg_df = df.groupby(["date", "uf"]).agg(**named_aggs)
# spatial_agg_df = df.iloc[:10000].groupby(["date", "uf"]).agg(**named_aggs)  # ### PARTIAL, just to test

spatial_agg_df

In [ ]:
# Visualize variables
# ---------------
fig = px.line(
    spatial_agg_df.reset_index(),
    x="date", y="mean_temp_med", color="uf"
)



# --- Save
save_tmp_plotly_fig(fig, "mean_temp_med_uf")

fig.show()

# Compare different spatial temperature aggregation methods
# --------------
df = spatial_agg_df.copy()

df["temp_diff"] = df["weighted_mean_temp_med"] - df["mean_temp_med"]
df["temp_squared_error"] = df["temp_diff"]**2


df

# Box plot
fig = px.box(
    df.reset_index(), x="uf", y="temp_diff",
    title="Temperature Difference (Weighted minus Simple Average) by UF"
)
fig.show()
save_tmp_plotly_fig(fig, "temp_diff_uf")

# --- Dispersion plot for one UF
uf = "PR"
_df = df.xs(uf, level="uf")

fig = px.scatter(
    _df.reset_index(), x="mean_temp_med", y="weighted_mean_temp_med",
    title=f"Plain vs weighted average temperature for UF = {uf}"
)
fig.add_scatter(
    x=[15, 34], y=[15, 34], mode="lines", line_color="gray", line_dash="dash",
)

fig.show()
save_tmp_plotly_fig(fig, f"temp_dispersion_{uf}")

# Episcanner data

In [ ]:
fpath = Path("../../data/episcanner/episcanner_dengue_2011_2026.csv")
episcanner_main_df = pd.read_csv(fpath)

episcanner_main_df

# # Convert some variable that were float but should be double - Needed only once, safe to delete
# df = episcanner_main_df
#
# df["year"] = df["year"].astype(int)
# df["ep_dur"] = df["ep_dur"].astype(int)
# df["geocode"] = df["geocode"].astype(int)
#
# df.to_csv(fpath, index=False)

In [ ]:
df = episcanner_main_df

# --- Plot distribution of gammas, just to check the range of values
from scipy.stats import gaussian_kde
gamma_kde = gaussian_kde(df["gamma"])

fig = px.histogram(
    df, x="gamma"
)
fig.show()
save_tmp_plotly_fig(fig, "episcanner_gamma_hist")

# --- Plot per-state distributions of key parameters, to see their spatial variability
year = 2024
y_variables = ["R0", "ep_dur"]

for y_variable in y_variables:
    fig = px.box(
        df.loc[df["year"] == year], x="uf", y=y_variable, title=f"Param: {y_variable}, year = {year}"
    )

    fig.show()
    name = f"episcanner_uf_dists/boxplot_{y_variable}_{year}"
    save_tmp_plotly_fig(fig, name)

# Ocean temperature

In [ ]:
imdc_ocean_df = pd.read_csv("../../data/data_imdc_2026/ocean_climate_oscillations.csv.gz", parse_dates=["date"])

imdc_ocean_df

In [ ]:
df = imdc_ocean_df

fig = px.line(df, x="date", y=["enso", "iod", "pdo"])
save_tmp_plotly_fig(fig, "ocean_temperature_oscillations.html")
fig.show()

# Climate forecast

In [ ]:
imdc_climate_forecast_df = pd.read_csv(
    "../../data/data_imdc_2026/forecasting_climate.csv.gz", parse_dates=["reference_month"], date_format="mixed"
)
# Note: NEED to include `date_format = "mixed"` since some stamps have hours and some don´t.

imdc_climate_forecast_df

In [ ]:
df = imdc_climate_forecast_df

# --- Include state (UF) and population information
df = df.merge(imdc_regional_df[["uf", "geocode"]], on="geocode")
df["year"] = df["reference_month"].dt.year
df = df.merge(imdc_population_df[:], on=["year", "geocode"])


# Calculate the average forecasted temperatures by the month of submission
# -----------------------
ref_month = 9  # September

df_to_group = df.loc[df["reference_month"].dt.month == ref_month]

# This operation:
#     For each municipality and year, take the average forecasted temp, humidity and precip over the forecast horizon
#     starting in the selected month. That's a temporal aggregation.
agg_df = df_to_group.groupby(["year", "geocode"]).agg(
    {
        "temp_med": "mean", "umid_med": "mean", "precip_tot": "mean",
        "uf": "first", "population": "first"
    }
).reset_index()

# --- Spatial aggregation - Weighted average of all municipalities of each state, yearwise
weighted_avg_func = lambda x: (x * df.loc[x.index, "population"]).sum() / df.loc[x.index, "population"].sum()
spatial_agg_df = agg_df.groupby(["year", "uf"]).agg({
        "temp_med": weighted_avg_func, "umid_med": weighted_avg_func, "precip_tot": weighted_avg_func,
}).reset_index()

# =========
years = spatial_agg_df["year"].unique()


for y_variable in ["temp_med", "umid_med", "precip_tot"]:
    fig = px.box(spatial_agg_df, x="uf", y=y_variable, title=f"Spatial average of {y_variable} - {years.min()}-{years.max()}")

    fig.show()
    save_tmp_plotly_fig(fig, f"climate_foecast_{y_variable}_uf")